# Generated by Django 4.1.7 on 2023-03-15 14:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank='False', default='none', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
