# Generated by Django 4.1.7 on 2023-03-15 14:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_signup_number_alter_signup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='signup',
            name='Number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank='False', default='none', max_length=128, primary_key='true', region=None, serialize=False),
        ),
    ]
