# Generated by Django 4.1.7 on 2023-03-15 14:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_signup_id_alter_signup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank='False', max_length=128, primary_key='true', region=None, serialize=False),
        ),
    ]
