# Generated by Django 4.1.7 on 2023-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_signup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='c_password',
            field=models.CharField(blank='false', max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(blank='false', max_length=100, null='false'),
        ),
    ]
